// Dummy setup for json data
module.exports = [
 {
  speakerId: "	String Unique speaker ID (autogenerated)",
  fullName: "	String	Speaker's full name",
  avatarUrl: " 	String	Speaker's avatar URL(local or remote URL)",
  jobTitle: " 	String	Speaker's job title",
  companyUrl: "	String(href link)	Work place URL of speaker",
  githubUrl: "	String(href link)	Github URL",
  linkedinUrl: "	String(href link)	Linkedin URL",
  twitterUrl: " 	String(href link)	Twitter URL",
  mediumUrl: "	String(href link)	Medium URL",
  codepenUrl: " 	String(href link)	Codepen URL",
  prevTalks: ["eventID array"]
 }
]